I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 109, in script
    show nina_surprised
Exception: In DynamicImage u'images/\u041d\u0438\u043d\u0430/[Originals]/nina_surprised.png': Could not find substitution 'Originals'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 109, in script
    show nina_surprised
  File "renpy/ast.py", line 1191, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1161, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 753, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "renpy/display/core.py", line 1103, in add
    thing.set_transform_event("show")
  File "renpy/display/transform.py", line 752, in set_transform_event
    self.child.set_transform_event(event)
  File "renpy/display/image.py", line 489, in set_transform_event
    return self.target.set_transform_event(event)
  File "renpy/display/image.py", line 718, in set_transform_event
    self.find_target()
  File "renpy/display/image.py", line 638, in find_target
    raise Exception("In DynamicImage %r: Could not find substitution '%s'." % (self.name, str(ke.args[0])))
Exception: In DynamicImage u'images/\u041d\u0438\u043d\u0430/[Originals]/nina_surprised.png': Could not find substitution 'Originals'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
В поезде с вампирами 1.0
Sun May 30 21:54:42 2021
